<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Add visitor ID fields to bookings table.
 *
 * These are required by the VMS (Visitor Management System) API to
 * generate a visitor pass / check-in code / QR code.
 *
 * Run: php artisan migrate
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::table('bookings', function (Blueprint $table) {
            // ── VMS visitor identity fields ────────────────────────────────
            // Stored on the booking so admin can reference them, and so a
            // retry to VMS can be made without re-asking the customer.
            $table->enum('id_type', [
                'national_id',
                'passport',
                'drivers_license',
                'other',
            ])->default('national_id')->after('customer_type');

            $table->string('id_number', 50)->nullable()->after('id_type');

            // ── VMS sync tracking ──────────────────────────────────────────
            // Stores the response from VMS so staff can look up visitor pass data.
            $table->string('vms_reference', 50)->nullable()->after('reference')
                ->comment('VMS booking reference, e.g. VMS000012');

            $table->string('vms_check_in_code', 20)->nullable()->after('vms_reference')
                ->comment('8-character alphanumeric check-in code from VMS');

            $table->string('vms_qr_code_url')->nullable()->after('vms_check_in_code')
                ->comment('URL to the QR code image generated by VMS');

            $table->timestamp('vms_synced_at')->nullable()->after('vms_qr_code_url')
                ->comment('When the booking was successfully synced to VMS');

            $table->index('vms_reference');
        });
    }

    public function down(): void
    {
        Schema::table('bookings', function (Blueprint $table) {
            $table->dropIndex(['vms_reference']);
            $table->dropColumn([
                'id_type',
                'id_number',
                'vms_reference',
                'vms_check_in_code',
                'vms_qr_code_url',
                'vms_synced_at',
            ]);
        });
    }
};
