<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeders.
     */
    public function run(): void
    {
        // ============================================
        // HOME FIBER PLANS
        // ============================================
        
        $homeLite = Product::create([
            'category_id' => Category::where('slug', 'home-fiber')->first()->id,
            'name' => 'Home Lite',
            'slug' => 'home-lite',
            'description' => 'Perfect for light internet users who need basic connectivity for browsing and email.',
            'short_description' => 'Affordable internet for basic home needs',
            'type' => 'internet_plan',
            'speed_mbps' => 8,
            'connection_type' => 'fiber',
            'plan_category' => 'home',
            'price_monthly' => 1999,
            'setup_fee' => 0,
            'features' => [
                'Unlimited internet access',
                'Moderate internet speed',
                'SD Movie & Music Streaming',
                'Fast web browsing',
                'SD TV programming',
                'E-learning & Online meetings',
            ],
            'technical_specs' => [
                'Technology' => 'Fiber to the Home (FTTH)',
                'Upload Speed' => '5 Mbps',
                'Data Cap' => 'Unlimited',
                'Contract' => '12 months',
            ],
            'is_active' => true,
            'is_featured' => false,
            'sort_order' => 1,
        ]);

        $homeStarter = Product::create([
            'category_id' => Category::where('slug', 'home-fiber')->first()->id,
            'name' => 'Home Starter',
            'slug' => 'home-starter',
            'description' => 'Great for families with multiple devices who enjoy HD streaming and gaming.',
            'short_description' => 'Perfect for families with multiple devices',
            'type' => 'internet_plan',
            'speed_mbps' => 20,
            'connection_type' => 'fiber',
            'plan_category' => 'home',
            'price_monthly' => 2499,
            'setup_fee' => 0,
            'features' => [
                'Unlimited internet access',
                'Up to 20 Mbps download',
                'HD Movie & Music Streaming',
                'Online gaming support',
                'Multiple device connectivity',
                'Standard router included',
            ],
            'technical_specs' => [
                'Technology' => 'Fiber to the Home (FTTH)',
                'Upload Speed' => '10 Mbps',
                'Data Cap' => 'Unlimited',
                'Router' => 'Dual-band WiFi',
            ],
            'is_active' => true,
            'is_featured' => false,
            'sort_order' => 2,
        ]);

        $homeFamily = Product::create([
            'category_id' => Category::where('slug', 'home-fiber')->first()->id,
            'name' => 'Home Family',
            'slug' => 'home-family',
            'description' => 'Our most popular home plan with blazing fast speeds for the whole family.',
            'short_description' => 'Most popular plan for connected homes',
            'type' => 'internet_plan',
            'speed_mbps' => 50,
            'connection_type' => 'fiber',
            'plan_category' => 'home',
            'price_monthly' => 3999,
            'setup_fee' => 0,
            'features' => [
                'Unlimited internet access',
                'Up to 50 Mbps download',
                '4K Ultra HD Streaming',
                'Online gaming with low latency',
                'Static IP address',
                'Mesh WiFi system included',
            ],
            'technical_specs' => [
                'Technology' => 'Fiber to the Home (FTTH)',
                'Upload Speed' => '25 Mbps',
                'Data Cap' => 'Unlimited',
                'Router' => 'Mesh WiFi System',
                'Static IP' => '1 included',
            ],
            'is_active' => true,
            'is_featured' => true,
            'badge' => 'Most Popular',
            'sort_order' => 3,
        ]);

        $homePremium = Product::create([
            'category_id' => Category::where('slug', 'home-fiber')->first()->id,
            'name' => 'Home Premium',
            'slug' => 'home-premium',
            'description' => 'Ultimate home internet experience with gigabit speeds and premium support.',
            'short_description' => 'Gigabit internet for power users',
            'type' => 'internet_plan',
            'speed_mbps' => 100,
            'connection_type' => 'fiber',
            'plan_category' => 'home',
            'price_monthly' => 5999,
            'setup_fee' => 0,
            'features' => [
                'Unlimited internet access',
                'Up to 1 Gbps download',
                '4K/8K Ultra HD Streaming',
                'Pro gaming support',
                'Static IP address',
                'Premium WiFi 6 router',
                'Free domain registration',
            ],
            'technical_specs' => [
                'Technology' => 'Fiber to the Home (FTTH)',
                'Upload Speed' => '500 Mbps',
                'Data Cap' => 'Unlimited',
                'Router' => 'WiFi 6 AX3000',
                'Static IP' => '1 included',
            ],
            'is_active' => true,
            'is_featured' => false,
            'sort_order' => 4,
        ]);

        // ============================================
        // BUSINESS FIBER PLANS
        // ============================================

        $businessStartup = Product::create([
            'category_id' => Category::where('slug', 'business-fiber')->first()->id,
            'name' => 'Business Startup',
            'slug' => 'business-startup',
            'description' => 'Reliable internet for small businesses and startups.',
            'short_description' => 'Reliable connectivity for small businesses',
            'type' => 'internet_plan',
            'speed_mbps' => 50,
            'connection_type' => 'fiber',
            'plan_category' => 'business',
            'price_monthly' => 5999,
            'setup_fee' => 5000,
            'features' => [
                'Unlimited business data',
                'Up to 50 Mbps download',
                'Static IP address',
                'SLA 99.5% uptime guarantee',
                'Priority installation',
                'Business hours support',
            ],
            'technical_specs' => [
                'Technology' => 'Fiber to the Business (FTTB)',
                'Upload Speed' => '25 Mbps',
                'SLA' => '99.5%',
                'Support' => 'Business hours',
            ],
            'is_active' => true,
            'is_featured' => false,
            'sort_order' => 1,
        ]);

        $businessGrowth = Product::create([
            'category_id' => Category::where('slug', 'business-fiber')->first()->id,
            'name' => 'Business Growth',
            'slug' => 'business-growth',
            'description' => 'Scalable solution for growing businesses with enhanced support.',
            'short_description' => 'Scale your business with dedicated connectivity',
            'type' => 'internet_plan',
            'speed_mbps' => 100,
            'connection_type' => 'fiber',
            'plan_category' => 'business',
            'price_monthly' => 9999,
            'setup_fee' => 7500,
            'features' => [
                'Unlimited business data',
                'Up to 100 Mbps download',
                'Multiple static IPs',
                'SLA 99.9% uptime guarantee',
                'DDoS protection',
                'Dedicated account manager',
            ],
            'technical_specs' => [
                'Technology' => 'Fiber to the Business (FTTB)',
                'Upload Speed' => '50 Mbps',
                'SLA' => '99.9%',
                'Support' => '24/7 priority',
                'Static IPs' => '5 included',
            ],
            'is_active' => true,
            'is_featured' => true,
            'badge' => 'Best Value',
            'sort_order' => 2,
        ]);

        $businessEnterprise = Product::create([
            'category_id' => Category::where('slug', 'business-fiber')->first()->id,
            'name' => 'Business Enterprise',
            'slug' => 'business-enterprise',
            'description' => 'Enterprise-grade connectivity for mission-critical operations.',
            'short_description' => 'Enterprise connectivity for mission-critical ops',
            'type' => 'internet_plan',
            'speed_mbps' => 500,
            'connection_type' => 'fiber',
            'plan_category' => 'business',
            'price_monthly' => 24999,
            'setup_fee' => 15000,
            'features' => [
                'Unlimited business data',
                'Up to 500 Mbps download',
                'Large IP block allocation',
                'SLA 99.99% uptime guarantee',
                'Advanced DDoS protection',
                '24/7 VIP support',
                'Cloud backup included',
            ],
            'technical_specs' => [
                'Technology' => 'Fiber to the Business (FTTB)',
                'Upload Speed' => '250 Mbps',
                'SLA' => '99.99%',
                'Support' => '24/7 VIP',
                'IP Block' => '/28 network',
            ],
            'is_active' => true,
            'is_featured' => false,
            'sort_order' => 3,
        ]);

        $businessCorporate = Product::create([
            'category_id' => Category::where('slug', 'business-fiber')->first()->id,
            'name' => 'Business Corporate',
            'slug' => 'business-corporate',
            'description' => 'Ultimate corporate solution with dedicated infrastructure and on-site support.',
            'short_description' => 'Ultimate corporate solution with dedicated line',
            'type' => 'internet_plan',
            'speed_mbps' => 1000,
            'connection_type' => 'fiber',
            'plan_category' => 'enterprise',
            'price_monthly' => 49999,
            'setup_fee' => 25000,
            'features' => [
                'Dedicated fiber line',
                'Up to 1 Gbps symmetric',
                'Unlimited IP addresses',
                'SLA 99.99% uptime guarantee',
                '24/7 on-site support',
                'Custom network solutions',
                'Dedicated account team',
            ],
            'technical_specs' => [
                'Technology' => 'Dedicated Fiber',
                'Upload Speed' => '1 Gbps symmetric',
                'SLA' => '99.99% + credits',
                'Support' => '24/7 on-site',
                'IP Block' => '/24 available',
            ],
            'is_active' => true,
            'is_featured' => false,
            'badge' => 'Enterprise',
            'sort_order' => 4,
        ]);

        // ============================================
        // VPS HOSTING PACKAGES
        // ============================================

        $vpsStarter = Product::create([
            'category_id' => Category::where('slug', 'vps-hosting')->first()->id,
            'name' => 'VPS Starter',
            'slug' => 'vps-starter',
            'description' => 'Perfect entry-level VPS for small websites and development environments.',
            'short_description' => 'Entry-level virtual private server',
            'type' => 'hosting_package',
            'price_monthly' => 2499,
            'price_quarterly' => 6999,
            'price_annually' => 24999,
            'setup_fee' => 0,
            'storage_gb' => 40,
            'bandwidth_gb' => 1000,
            'email_accounts' => 10,
            'databases' => 5,
            'domains_allowed' => 3,
            'ssl_included' => true,
            'backup_included' => true,
            'features' => [
                '1 Core CPU',
                '2 GB Guaranteed RAM',
                '40 GB 100% SSD Storage',
                'KVM Virtualization',
                'Unlimited Bandwidth',
                'Full Root Access',
                'DDoS Protection',
                '100 Mbit/s Port',
                'FREE cPanel License',
                '1 IPv4 Address',
            ],
            'technical_specs' => [
                'Virtualization' => 'KVM',
                'CPU' => '1 Core Dedicated',
                'RAM' => '2 GB Guaranteed',
                'Storage' => '40 GB SSD',
                'Bandwidth' => 'Unlimited',
                'Port Speed' => '100 Mbit/s',
                'IPv4' => '1 Address',
                'IPv6' => '64 Addresses',
                'Control Panel' => 'cPanel (optional)',
            ],
            'is_active' => true,
            'is_featured' => false,
            'sort_order' => 1,
        ]);

        $vpsProfessional = Product::create([
            'category_id' => Category::where('slug', 'vps-hosting')->first()->id,
            'name' => 'VPS Professional',
            'slug' => 'vps-professional',
            'description' => 'Balanced VPS package for growing websites and applications.',
            'short_description' => 'Balanced performance for growing sites',
            'type' => 'hosting_package',
            'price_monthly' => 3999,
            'price_quarterly' => 10999,
            'price_annually' => 39999,
            'setup_fee' => 0,
            'storage_gb' => 80,
            'bandwidth_gb' => 2000,
            'email_accounts' => 25,
            'databases' => 10,
            'domains_allowed' => 5,
            'ssl_included' => true,
            'backup_included' => true,
            'features' => [
                '2 Cores CPU',
                '4 GB Guaranteed RAM',
                '80 GB 100% SSD Storage',
                'KVM Virtualization',
                'Unlimited Bandwidth',
                'Full Root Access',
                'DDoS Protection',
                '200 Mbit/s Port',
                'FREE cPanel License (3 accounts)',
                '1 IPv4 Address',
                'Priority Support',
            ],
            'technical_specs' => [
                'Virtualization' => 'KVM',
                'CPU' => '2 Cores Dedicated',
                'RAM' => '4 GB Guaranteed',
                'Storage' => '80 GB SSD',
                'Bandwidth' => 'Unlimited',
                'Port Speed' => '200 Mbit/s',
                'IPv4' => '1 Address',
                'IPv6' => '64 Addresses',
                'cPanel Accounts' => '3 included',
            ],
            'is_active' => true,
            'is_featured' => true,
            'badge' => 'Popular',
            'sort_order' => 2,
        ]);

        // This is the VPS package you specifically mentioned
        $vpsUltimate = Product::create([
            'category_id' => Category::where('slug', 'vps-hosting')->first()->id,
            'name' => 'VPS Ultimate',
            'slug' => 'vps-ultimate',
            'description' => 'High-performance VPS with premium resources for demanding applications.',
            'short_description' => 'High-performance VPS for demanding applications',
            'type' => 'hosting_package',
            'price_monthly' => 4999,
            'price_quarterly' => 13999,
            'price_annually' => 49999,
            'setup_fee' => 0,
            'storage_gb' => 150,
            'bandwidth_gb' => 5000,
            'email_accounts' => 50,
            'databases' => 25,
            'domains_allowed' => 10,
            'ssl_included' => true,
            'backup_included' => true,
            'features' => [
                'Ksh 4,000 / Month Incl. VAT',
                '2 Cores CPU',
                '8 GB Guaranteed RAM',
                '80 GB 100% SSD Disk Space',
                'KVM Virtualization',
                'Unlimited Bandwidth',
                'Full Root Access',
                'DDoS Protection',
                '400 Mbit/s Port',
                'FREE cPanel License (5 cPanel accounts)',
                '1 IPv4 Address',
                '64 Network IPv6 Address',
            ],
            'technical_specs' => [
                'Virtualization' => 'KVM',
                'CPU' => '2 Cores Dedicated',
                'RAM' => '8 GB Guaranteed',
                'Storage' => '80 GB SSD',
                'Bandwidth' => 'Unlimited',
                'Port Speed' => '400 Mbit/s',
                'IPv4' => '1 Address',
                'IPv6' => '64 Addresses',
                'cPanel Accounts' => '5 included',
            ],
            'is_active' => true,
            'is_featured' => false,
            'sort_order' => 3,
        ]);

        $vpsEnterprise = Product::create([
            'category_id' => Category::where('slug', 'vps-hosting')->first()->id,
            'name' => 'VPS Enterprise',
            'slug' => 'vps-enterprise',
            'description' => 'Maximum performance VPS for large-scale applications and high-traffic websites.',
            'short_description' => 'Maximum performance for enterprise workloads',
            'type' => 'hosting_package',
            'price_monthly' => 8999,
            'price_quarterly' => 24999,
            'price_annually' => 89999,
            'setup_fee' => 0,
            'storage_gb' => 500,
            'bandwidth_gb' => 10000,
            'email_accounts' => 100,
            'databases' => 50,
            'domains_allowed' => 25,
            'ssl_included' => true,
            'backup_included' => true,
            'features' => [
                '4 Cores CPU',
                '16 GB Guaranteed RAM',
                '200 GB 100% SSD Storage',
                'KVM Virtualization',
                'Unlimited Bandwidth',
                'Full Root Access',
                'DDoS Protection',
                '1 Gbit/s Port',
                'FREE cPanel License (Unlimited)',
                '2 IPv4 Addresses',
                'Priority Support',
                'Managed Services Available',
            ],
            'technical_specs' => [
                'Virtualization' => 'KVM',
                'CPU' => '4 Cores Dedicated',
                'RAM' => '16 GB Guaranteed',
                'Storage' => '200 GB SSD',
                'Bandwidth' => 'Unlimited',
                'Port Speed' => '1 Gbit/s',
                'IPv4' => '2 Addresses',
                'IPv6' => '64 Addresses',
                'cPanel Accounts' => 'Unlimited',
            ],
            'is_active' => true,
            'is_featured' => false,
            'sort_order' => 4,
        ]);

        // ============================================
        // WEB HOSTING PACKAGES
        // ============================================

        $webStarter = Product::create([
            'category_id' => Category::where('slug', 'web-hosting')->first()->id,
            'name' => 'Web Starter',
            'slug' => 'web-starter',
            'description' => 'Affordable shared hosting for small personal websites and blogs.',
            'short_description' => 'Perfect for personal websites and blogs',
            'type' => 'hosting_package',
            'price_monthly' => 499,
            'price_annually' => 4999,
            'storage_gb' => 5,
            'bandwidth_gb' => 50,
            'email_accounts' => 2,
            'databases' => 1,
            'domains_allowed' => 1,
            'ssl_included' => true,
            'backup_included' => false,
            'features' => [
                '5 GB SSD Storage',
                '50 GB Monthly Bandwidth',
                '2 Email Accounts',
                '1 MySQL Database',
                '1 Domain Allowed',
                'Free SSL Certificate',
                'cPanel Control Panel',
                '99.9% Uptime',
            ],
            'is_active' => true,
            'is_featured' => false,
            'sort_order' => 1,
        ]);

        $webProfessional = Product::create([
            'category_id' => Category::where('slug', 'web-hosting')->first()->id,
            'name' => 'Web Professional',
            'slug' => 'web-professional',
            'description' => 'Ideal for small business websites with enhanced resources.',
            'short_description' => 'Great for small business websites',
            'type' => 'hosting_package',
            'price_monthly' => 1499,
            'price_annually' => 14999,
            'storage_gb' => 25,
            'bandwidth_gb' => 200,
            'email_accounts' => 10,
            'databases' => 5,
            'domains_allowed' => 3,
            'ssl_included' => true,
            'backup_included' => true,
            'features' => [
                '25 GB SSD Storage',
                '200 GB Monthly Bandwidth',
                '10 Email Accounts',
                '5 MySQL Databases',
                '3 Domains Allowed',
                'Free SSL Certificate',
                'cPanel Control Panel',
                'Daily Backups',
                '99.9% Uptime',
            ],
            'is_active' => true,
            'is_featured' => true,
            'badge' => 'Best Seller',
            'sort_order' => 2,
        ]);

        $webBusiness = Product::create([
            'category_id' => Category::where('slug', 'web-hosting')->first()->id,
            'name' => 'Web Business',
            'slug' => 'web-business',
            'description' => 'Comprehensive hosting for e-commerce and high-traffic websites.',
            'short_description' => 'Complete solution for online businesses',
            'type' => 'hosting_package',
            'price_monthly' => 3499,
            'price_annually' => 34999,
            'storage_gb' => 100,
            'bandwidth_gb' => 500,
            'email_accounts' => 50,
            'databases' => 20,
            'domains_allowed' => 10,
            'ssl_included' => true,
            'backup_included' => true,
            'features' => [
                '100 GB SSD Storage',
                '500 GB Monthly Bandwidth',
                '50 Email Accounts',
                '20 MySQL Databases',
                '10 Domains Allowed',
                'Free SSL Certificate',
                'cPanel Control Panel',
                'Daily Backups',
                'Priority Support',
                'E-commerce Optimized',
            ],
            'is_active' => true,
            'is_featured' => false,
            'sort_order' => 3,
        ]);

        // ============================================
        // RESELLER HOSTING PACKAGES
        // ============================================

        $resellerStarter = Product::create([
            'category_id' => Category::where('slug', 'reseller-hosting')->first()->id,
            'name' => 'Reseller Starter',
            'slug' => 'reseller-starter',
            'description' => 'Start your own hosting business with ample resources.',
            'short_description' => 'Launch your hosting business',
            'type' => 'hosting_package',
            'price_monthly' => 2999,
            'price_annually' => 29999,
            'storage_gb' => 50,
            'bandwidth_gb' => 500,
            'domains_allowed' => 10,
            'features' => [
                '50 GB SSD Storage',
                '500 GB Monthly Bandwidth',
                'Resell cPanel Accounts',
                'WHM Access',
                'Free SSL for All Clients',
                'Daily Backups',
                'White-label Branding',
                'Support for 10 Clients',
            ],
            'is_active' => true,
            'is_featured' => false,
            'sort_order' => 1,
        ]);

        $resellerPro = Product::create([
            'category_id' => Category::where('slug', 'reseller-hosting')->first()->id,
            'name' => 'Reseller Pro',
            'slug' => 'reseller-pro',
            'description' => 'Scale your reseller business with more resources.',
            'short_description' => 'Scale your hosting business',
            'type' => 'hosting_package',
            'price_monthly' => 5999,
            'price_annually' => 59999,
            'storage_gb' => 150,
            'bandwidth_gb' => 2000,
            'domains_allowed' => 50,
            'features' => [
                '150 GB SSD Storage',
                '2 TB Monthly Bandwidth',
                'Unlimited cPanel Accounts',
                'WHM Access',
                'Free SSL for All Clients',
                'Daily Backups',
                'White-label Branding',
                'Support for 50 Clients',
                'Priority Support',
            ],
            'is_active' => true,
            'is_featured' => true,
            'badge' => 'Recommended',
            'sort_order' => 2,
        ]);

        $resellerUltimate = Product::create([
            'category_id' => Category::where('slug', 'reseller-hosting')->first()->id,
            'name' => 'Reseller Ultimate',
            'slug' => 'reseller-ultimate',
            'description' => 'Maximum resources for established reseller businesses.',
            'short_description' => 'Maximum resources for resellers',
            'type' => 'hosting_package',
            'price_monthly' => 9999,
            'price_annually' => 99999,
            'storage_gb' => 500,
            'bandwidth_gb' => 5000,
            'domains_allowed' => 'unlimited',
            'features' => [
                '500 GB SSD Storage',
                '5 TB Monthly Bandwidth',
                'Unlimited cPanel Accounts',
                'WHM Access',
                'Free SSL for All Clients',
                'Hourly Backups',
                'White-label Branding',
                'Unlimited Client Accounts',
                'VIP Support',
                'API Access',
            ],
            'is_active' => true,
            'is_featured' => false,
            'sort_order' => 3,
        ]);

        // ============================================
        // DEDICATED SERVERS
        // ============================================

        $dedicatedBasic = Product::create([
            'category_id' => Category::where('slug', 'dedicated-servers')->first()->id,
            'name' => 'Dedicated Basic',
            'slug' => 'dedicated-basic',
            'description' => 'Entry-level dedicated server for growing websites.',
            'short_description' => 'Your own server at affordable price',
            'type' => 'hosting_package',
            'price_monthly' => 8999,
            'storage_gb' => 500,
            'bandwidth_gb' => 5000,
            'features' => [
                'Intel Xeon E-2300 Processor',
                '16 GB DDR4 RAM',
                '500 GB SSD Storage',
                '5 TB Monthly Bandwidth',
                '1 Gbit/s Port',
                '5 IPv4 Addresses',
                'DDoS Protection',
                '24/7 Support',
                'Hardware Replacement',
            ],
            'is_active' => true,
            'is_featured' => false,
            'sort_order' => 1,
        ]);

        $dedicatedPro = Product::create([
            'category_id' => Category::where('slug', 'dedicated-servers')->first()->id,
            'name' => 'Dedicated Pro',
            'slug' => 'dedicated-pro',
            'description' => 'High-performance dedicated server for demanding applications.',
            'short_description' => 'High-performance for demanding workloads',
            'type' => 'hosting_package',
            'price_monthly' => 15999,
            'storage_gb' => 1000,
            'bandwidth_gb' => 10000,
            'features' => [
                'Intel Xeon Silver Processor',
                '32 GB DDR4 RAM',
                '1 TB NVMe SSD Storage',
                '10 TB Monthly Bandwidth',
                '1 Gbit/s Port',
                '10 IPv4 Addresses',
                'DDoS Protection',
                '24/7 VIP Support',
                'Hardware Replacement',
                'RAID Configuration',
            ],
            'is_active' => true,
            'is_featured' => true,
            'badge' => 'Popular',
            'sort_order' => 2,
        ]);

        $dedicatedEnterprise = Product::create([
            'category_id' => Category::where('slug', 'dedicated-servers')->first()->id,
            'name' => 'Dedicated Enterprise',
            'slug' => 'dedicated-enterprise',
            'description' => 'Maximum performance for mission-critical enterprise applications.',
            'short_description' => 'Enterprise-grade dedicated server',
            'type' => 'hosting_package',
            'price_monthly' => 29999,
            'storage_gb' => 2000,
            'bandwidth_gb' => 20000,
            'features' => [
                'Dual Intel Xeon Gold Processors',
                '64 GB DDR4 RAM',
                '2 TB NVMe SSD Storage',
                'Unlimited Bandwidth',
                '10 Gbit/s Port',
                '25 IPv4 Addresses',
                'Advanced DDoS Protection',
                '24/7 VIP Support',
                'Hardware Replacement',
                'RAID Configuration',
                'Custom Configuration',
            ],
            'is_active' => true,
            'is_featured' => false,
            'sort_order' => 3,
        ]);

        // ============================================
        // DOMAIN REGISTRATION
        // ============================================

        $domainKE = Product::create([
            'category_id' => Category::where('slug', 'domain-ke')->first()->id,
            'name' => '.KE Domain Registration',
            'slug' => 'domain-ke',
            'description' => 'Register your .ke domain name for your Kenyan business.',
            'short_description' => 'Get your .ke domain today',
            'type' => 'domain',
            'price_annually' => 1500,
            'features' => [
                '.ke Domain Registration',
                'Free DNS Management',
                'Domain Privacy Protection',
                'Easy Domain Transfer',
                'Renewal Reminders',
            ],
            'is_active' => true,
            'is_featured' => true,
            'sort_order' => 1,
        ]);

        $domainCOM = Product::create([
            'category_id' => Category::where('slug', 'domain-com')->first()->id,
            'name' => '.COM Domain Registration',
            'slug' => 'domain-com',
            'description' => 'Register the world's most popular .com domain.',
            'short_description' => 'World\'s most popular domain',
            'type' => 'domain',
            'price_annually' => 1200,
            'features' => [
                '.com Domain Registration',
                'Free DNS Management',
                'Domain Privacy Protection',
                'Easy Domain Transfer',
                'Instant Registration',
            ],
            'is_active' => true,
            'is_featured' => false,
            'sort_order' => 1,
        ]);

        $domainNET = Product::create([
            'category_id' => Category::where('slug', 'domain-other')->first()->id,
            'name' => '.NET Domain Registration',
            'slug' => 'domain-net',
            'description' => 'Register a professional .net domain for your business.',
            'short_description' => 'Professional .net domain',
            'type' => 'domain',
            'price_annually' => 1400,
            'features' => [
                '.net Domain Registration',
                'Free DNS Management',
                'Domain Privacy Protection',
                'Easy Domain Transfer',
            ],
            'is_active' => true,
            'is_featured' => false,
            'sort_order' => 2,
        ]);

        // ============================================
        // WEB DEVELOPMENT PACKAGES
        // ============================================

        $webdevBasic = Product::create([
            'category_id' => Category::where('slug', 'static-websites')->first()->id,
            'name' => 'Basic Website',
            'slug' => 'web-development-basic',
            'description' => 'Professional static website for small businesses.',
            'short_description' => 'Professional static website',
            'type' => 'web_development',
            'price_one_time' => 15000,
            'pages_included' => 5,
            'revisions_included' => 2,
            'delivery_days' => 7,
            'features' => [
                'Up to 5 Pages',
                'Responsive Design',
                'Contact Form',
                'Social Media Integration',
                'Basic SEO Setup',
                '2 Revision Rounds',
                '7 Days Delivery',
            ],
            'is_active' => true,
            'is_featured' => false,
            'sort_order' => 1,
        ]);

        $webdevStandard = Product::create([
            'category_id' => Category::where('slug', 'dynamic-websites')->first()->id,
            'name' => 'Standard Website',
            'slug' => 'web-development-standard',
            'description' => 'Dynamic CMS-based website with easy content management.',
            'short_description' => 'Dynamic CMS website',
            'type' => 'web_development',
            'price_one_time' => 35000,
            'pages_included' => 15,
            'revisions_included' => 3,
            'delivery_days' => 14,
            'features' => [
                'Up to 15 Pages',
                'CMS (WordPress/Laravel)',
                'Admin Dashboard',
                'Contact & Booking Forms',
                'Blog Integration',
                'Basic SEO Package',
                '3 Revision Rounds',
                '14 Days Delivery',
            ],
            'is_active' => true,
            'is_featured' => true,
            'badge' => 'Popular',
            'sort_order' => 2,
        ]);

        $webdevEcommerce = Product::create([
            'category_id' => Category::where('slug', 'ecommerce-websites')->first()->id,
            'name' => 'E-Commerce Website',
            'slug' => 'web-development-ecommerce',
            'description' => 'Complete online store with payment integration.',
            'short_description' => 'Full-featured online store',
            'type' => 'web_development',
            'price_one_time' => 75000,
            'pages_included' => 25,
            'revisions_included' => 5,
            'delivery_days' => 30,
            'features' => [
                'Up to 25 Product Pages',
                'Shopping Cart',
                'Payment Gateway Integration',
                'Order Management',
                'Inventory System',
                'Customer Accounts',
                'Advanced SEO Package',
                '5 Revision Rounds',
                '30 Days Delivery',
            ],
            'is_active' => true,
            'is_featured' => false,
            'sort_order' => 3,
        ]);

        $this->command->info('Products seeded successfully!');
    }
}

